"""Real end-to-end render.

This is the test that proves the system actually works: it runs the complete
pipeline - topic, script, scenes, narration, footage selection, FFmpeg
assembly, subtitles, quality control and metadata - and produces a genuine
1080p MP4 with real audio.

It uses synthetic footage generated by FFmpeg and the offline TTS engine, so
it needs no API keys and no network access. It is the same code path a real
run uses; only the footage source and the length differ.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vidfactory.config import load_config
from vidfactory.database import Database
from vidfactory.ffmpeg_utils import probe_media
from vidfactory.pipeline import VideoPipeline
from vidfactory.testassets import build_test_library, clips_needed_for

pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def rendered(tmp_path_factory, request):
    """Render one short video once and share it across the assertions."""

    if not __import__("vidfactory.ffmpeg_utils", fromlist=["x"]).ffmpeg_available():
        pytest.skip("ffmpeg is required for the integration test")

    root = tmp_path_factory.mktemp("integration")
    clips_dir = root / "clips"
    # One distinct clip per shot, so the render is held to the same zero-reuse
    # rule as production rather than being excused for being a test.
    build_test_library(
        clips_dir, count=clips_needed_for(0.7), seconds=10.0, width=1920, height=1080
    )

    repo_root = Path(__file__).resolve().parents[1]
    config = load_config(
        repo_root / "config.yaml",
        overrides={
            "video.duration_minutes": 0.7,
            "video.preset": "ultrafast",
            "video.crf": 30,
            "video.motion": "subtle",
            "sources.pexels": False,
            "sources.pixabay": False,
            "sources.local": True,
            "sources.local_directory": str(clips_dir),
            "sources.min_source_seconds": 4.0,
            "tts.engine": "auto",
            "output.directory": str(root / "output"),
            "quality.min_file_mb": 0.05,
            "youtube.upload_enabled": False,
        },
    )
    database = Database(root / "factory.db")
    pipeline = VideoPipeline(
        config,
        database=database,
        workdir=root / "work",
        run_id="integration",
        state_dir=root / "state",
    )
    result = pipeline.run(topic_text="25 Small Living Room Ideas That Make Any Space Look Bigger")
    yield result, config, database, root
    database.close()


def test_a_real_mp4_was_produced(rendered):
    result, *_ = rendered
    assert result.video_path.exists()
    assert result.video_path.stat().st_size > 50_000


def test_video_is_1080p_h264_with_aac_audio(rendered):
    result, *_ = rendered
    info = probe_media(result.video_path)
    assert info.width == 1920
    assert info.height == 1080
    assert info.video_codec == "h264"
    assert info.audio_codec == "aac"
    assert info.has_video and info.has_audio


def test_video_is_between_thirty_and_ninety_seconds(rendered):
    result, *_ = rendered
    info = probe_media(result.video_path)
    assert 25.0 <= info.duration <= 120.0


def test_video_length_matches_the_narration(rendered):
    result, config, *_ = rendered
    info = probe_media(result.video_path)
    tail = float(config.get("video.tail_seconds", 1.2))
    # The renderer pins the output to narration + tail.
    assert abs(info.duration - (result.duration)) < 0.5
    assert info.duration > tail


def test_quality_control_passed(rendered):
    result, *_ = rendered
    assert result.report.passed is True
    assert not result.report.failures


def test_editorial_quality_control_passed(rendered):
    """No repeated source footage, and the ideas match the title."""

    result, *_ = rendered
    assert result.editorial is not None
    assert result.editorial.passed, [c.detail for c in result.editorial.failures]
    assert result.editorial.metrics["source_video_reuse_count"] == 0
    assert result.editorial.metrics["unique_source_ratio"] >= 0.95


def test_every_shot_uses_a_different_source_video(rendered):
    """The defect this whole upgrade exists to prevent."""

    result, _, _, root = rendered
    import json as _json

    payload = _json.loads(
        (result.video_path.parent / "editorial_quality_report.json").read_text(encoding="utf-8")
    )
    assert payload["source_video_reuse_count"] == 0
    assert payload["unique_source_videos"] == payload["shot_count"]


def test_no_black_opening_frame(rendered):
    from vidfactory.quality_control import has_black_start

    result, *_ = rendered
    assert has_black_start(result.video_path) is False


def test_all_expected_artifacts_exist(rendered):
    result, _, _, root = rendered
    output_dir = result.video_path.parent
    for name in (
        "final_video.mp4",
        "subtitles.srt",
        "script.txt",
        "script.json",
        "scenes.json",
        "metadata.json",
        "video_sources.json",
        "quality_report.json",
    ):
        assert (output_dir / name).exists(), name


def test_subtitles_are_valid_and_in_range(rendered):
    result, *_ = rendered
    content = result.subtitles_path.read_text(encoding="utf-8")
    assert content.strip()
    assert content.startswith("1\n")
    assert "-->" in content
    duration = probe_media(result.video_path).duration
    # Every cue must finish before the video does.
    last_line = [line for line in content.splitlines() if "-->" in line][-1]
    end = last_line.split("-->")[1].strip()
    hours, minutes, rest = end.split(":")
    seconds = float(rest.replace(",", "."))
    total = int(hours) * 3600 + int(minutes) * 60 + seconds
    assert total <= duration + 1.0


def test_metadata_is_complete(rendered):
    result, *_ = rendered
    payload = json.loads(result.metadata_path.read_text(encoding="utf-8"))
    assert payload["title"]
    assert payload["description"]
    assert payload["tags"]
    assert payload["chapters"]
    assert payload["chapters"][0]["time"] == "0:00"
    assert payload["privacy_status"] == "private"


def test_sources_are_recorded_with_attribution(rendered):
    result, *_ = rendered
    payload = json.loads(result.sources_path.read_text(encoding="utf-8"))
    assert payload["clips"]
    for clip in payload["clips"]:
        assert clip["provider"]
        assert clip["provider_id"]
        assert clip["license"]
    assert "original" in payload["note"].lower()


def test_history_was_persisted(rendered):
    result, _, database, root = rendered
    assert database.stats()["videos"] == 1
    assert database.stats()["clips"] >= 1
    assert database.has_topic_slug(result.topic.slug)
    assert (root / "state" / "topics.json").exists()


def test_the_script_is_original_prose(rendered):
    result, *_ = rendered
    text = result.script_path.read_text(encoding="utf-8")
    assert len(text.split()) > 60
    # Flowing narration, not a bullet list or a template dump.
    assert "\u2022" not in text
    assert "<|" not in text
    sentences = [s for s in text.split(".") if len(s.split()) > 4]
    assert len(sentences) >= 5
    # The formulaic connectives that made v1 sound generated must be gone.
    for phrase in ("The thinking behind this is simple", "Here is how to apply it"):
        assert phrase not in text


def test_temporary_footage_was_cleaned_up(rendered):
    _, _, _, root = rendered
    assert not (root / "work" / "clips").exists()
    assert not (root / "work" / "render").exists()
